app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, DateField
from wtforms.validators import DataRequired, Email


# Login screen
class LoginForm(FlaskForm):
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')


# Home screen
class ScrapeForm(FlaskForm):
    email_folder = StringField('Email Folder to Search', validators=[DataRequired()])
    date = DateField('Search Until (mm/dd/yyyy)', validators=[DataRequired()], format='%m/%d/%Y')
    download = SubmitField('Download')

app/__init__.py
from flask import Flask
from app.config import Config


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    from app.main.routes import main
    app.register_blueprint(main)

    return app

app/main/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, Response, session
from app.main.forms import LoginForm, ScrapeForm
from app.main.mail import ScrapeEmails, validate_email

main = Blueprint('main', __name__)


@main.route("/home", methods=['GET', 'POST'])
def home():
    form = ScrapeForm()
    # if payment email sender and target date ar valid, save info in session and proceed to download a csv list
    if form.validate_on_submit():
        session["email_folder"] = form.email_folder.data
        session["date"] = form.date.data
        return redirect(url_for('main.downloadCSV'))
    return render_template('home.html', title='Home', form=form)


@main.route("/downloadCSV")
def downloadCSV():
    # collect data from session and scrape client emails
    userEmail = session.get("email", None)
    userPass = session.get("pass", None)
    emailFolder = session.get("email_folder", None)
    stopDate = session.get("date", None)
    s = ScrapeEmails(emailFolder, stopDate)
    firstNameList, lastNameList, emailList = s.mail_list(userEmail, userPass)
    # if at least one client email was scraped, convert list to csv and download, otherwise advise user that no
    # client emails were found.
    if len(emailList) > 1:
        csv = ''
        for first_name, last_name, email in zip(firstNameList, lastNameList, emailList):
            csv = csv + first_name + ',' + last_name + ',' + email + '\n'
        return Response(
            csv,
            mimetype="text/csv",
            headers={"Content-disposition":
                         "attachment; filename=email_list.csv"})
    elif len(emailList) == 1:
        flash(f'There are no emails from in the folder {emailFolder} for the specified time frame.', 'danger')
        return redirect(url_for('main.home'))
    else:
        flash(f'The folder {emailFolder} does not exist in {userEmail}.', 'danger')
        return redirect(url_for('main.home'))

@main.route("/", methods=['GET', 'POST'])
@main.route("/login", methods=['GET', 'POST'])
def login():
    form = LoginForm()
    # if user email and password are valid, save info in session and direct to download/scraping home page
    if form.validate_on_submit():
        mail = validate_email(form.email.data, form.password.data)
        if mail:
            session["email"] = form.email.data
            session["pass"] = form.password.data
            flash('You have been logged in!', 'success')
            return redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check username and password', 'danger')
    return render_template('login.html', title='Login', form=form)

app/templates/home.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Get Emails</legend>
            <div class="form-group">
                {{ form.email_folder.label(class="form-control-label") }}
                {% if form.email_folder.errors %}
                    {{ form.email_folder(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email_folder.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email_folder(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.date.label(class="form-control-label") }}
                {% if form.date.errors %}
                    {{ form.date(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.date.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.date(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.download(class="btn btn-outline-info btn-lg btn-block") }}
        </div>
    </form>
</div>
{% endblock content %}

app/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Email Getter - {{ title }}</title>
    {% else %}
        <title>Email Getter</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Email Getter</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="{{ url_for('main.login') }}">Login</a>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>How to use Email Getter</h3>
              <p class='text-muted'>1. Log in using the email and password associated with the email address that your PayPal emails are sent to.</p>
              <p class='text-muted'>2. On the next page, enter the email folder at which your client emails are filed.</p>
              <p class='text-muted'>3. Next, enter the date for when the algorithm should stop searching.</p>
              <p class='text-muted'>4. Finally, click download.  This might take a while depending on how deep into your emails you are searching.</p>
          </div>
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

app/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>

{% endblock content %}